server:
  port: 9090 # ui：http://127.0.0.1:9090/zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false #解决报错 The meter you are attempting to register has keys [method, status, uri].